# Generated by Django 6.0.4 on 2026-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_directmessage_alter_post_id_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='encrypted_ecc_key',
            field=models.TextField(default='{}'),
        ),
    ]
