# Generated by Django 6.0.4 on 2026-05-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_directmessage_encrypted_ecc_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='encrypted_ecc_key',
        ),
    ]
