# Generated by Django 6.0.4 on 2026-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_add_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='encrypted_ecc_key',
            field=models.TextField(default='[]'),
        ),
    ]
