# Generated by Django 6.0.4 on 2026-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
