# Generated by Django 6.0.4 on 2026-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
